/**
 * This file was generated by the JPA Modeler
 */
package com.hellokoding.account.Models;

import org.springframework.transaction.annotation.Transactional;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "discountrule")
@Transactional
public class Discountrule implements Serializable {

    @Column(name = "DRId", table = "discountrule", nullable = false)
    @Id
    private Long dRId;

    @Column(name = "DiscountValue", table = "discountrule", precision = 12)
    @Basic
    private Float discountValue;

    @Column(name = "DiscountProcent", table = "discountrule", precision = 12)
    @Basic
    private Float discountProcent;

    @OneToMany(targetEntity = Itemdiscount.class, mappedBy = "discountrule1")
    private List<Itemdiscount> itemdiscounts1;

    public Long getdRId() {
        return this.dRId;
    }

    public void setdRId(Long dRId) {
        this.dRId = dRId;
    }

    public Float getDiscountValue() {
        return this.discountValue;
    }

    public void setDiscountValue(Float discountValue) {
        this.discountValue = discountValue;
    }

    public Float getDiscountProcent() {
        return this.discountProcent;
    }

    public void setDiscountProcent(Float discountProcent) {
        this.discountProcent = discountProcent;
    }

    public List<Itemdiscount> getItemdiscounts1() {
        return this.itemdiscounts1;
    }

    public void setItemdiscounts1(List<Itemdiscount> itemdiscounts1) {
        this.itemdiscounts1 = itemdiscounts1;
    }

}
