/**
 * This file was generated by the JPA Modeler
 */
package com.hellokoding.account.Models;

import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "itemdiscount")
@Transactional
public class Itemdiscount implements Serializable {

    @Column(name = "IDid", table = "itemdiscount", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("IDid")
    private Long IDid;

    @ManyToOne(targetEntity = Item.class)
    private Item item1;

    @ManyToOne(targetEntity = Discountrule.class)
    private Discountrule discountrule1;

    public Long getIDid() {
        return this.IDid;
    }

    public void setIDid(Long IDid) {
        this.IDid = IDid;
    }

    public Item getItem1() {
        return this.item1;
    }

    public void setItem1(Item item1) {
        this.item1 = item1;
    }

    public Discountrule getDiscountrule1() {
        return this.discountrule1;
    }

    public void setDiscountrule1(Discountrule discountrule1) {
        this.discountrule1 = discountrule1;
    }

}
