/**
 * This file was generated by the JPA Modeler
 */
package com.hellokoding.account.Models;

import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "payment")
@Transactional
public class Payment implements Serializable {

    @Column(name = "PaymentId", table = "payment", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long paymentId;

    @Column(name = "PaymentInfo", table = "payment")
    @Basic
    private String paymentInfo;

    @Column(name = "paymentDate", table = "payment")
    @Basic
    private Date paymentDate;

    @ManyToOne(targetEntity = Paymenttype.class)
    private Paymenttype paymenttype1;

    @ManyToOne(targetEntity = So.class)
    private So so1;

    @ManyToOne(targetEntity = Paymentbill.class)
    private Paymentbill paymentbill1;

    public Long getPaymentId() {
        return this.paymentId;
    }

    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    public String getPaymentInfo() {
        return this.paymentInfo;
    }

    public void setPaymentInfo(String paymentInfo) {
        this.paymentInfo = paymentInfo;
    }

    public Paymenttype getPaymenttype1() {
        return this.paymenttype1;
    }

    public void setPaymenttype1(Paymenttype paymenttype1) {
        this.paymenttype1 = paymenttype1;
    }

    public So getSo1() {
        return this.so1;
    }

    public void setSo1(So so1) {
        this.so1 = so1;
    }

    public Paymentbill getPaymentbill1() {
        return this.paymentbill1;
    }

    public void setPaymentbill1(Paymentbill paymentbill1) {
        this.paymentbill1 = paymentbill1;
    }

    public Date getPaymentDate() {
        return paymentDate;
    }

    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }
}
