/**
 * This file was generated by the JPA Modeler
 */
package com.hellokoding.account.Models;

import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "paymenttype")
@Transactional
public class Paymenttype implements Serializable {

    @Column(name = "PTId", table = "paymenttype", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long pTId;

    @Column(name = "TypeName", table = "paymenttype")
    @Basic
    private String typeName;

    @OneToMany(targetEntity = Payment.class, mappedBy = "paymenttype1")
    private List<Payment> payments1;

    public Long getPTId() {
        return this.pTId;
    }

    public void setPTId(Long pTId) {
        this.pTId = pTId;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public List<Payment> getPayments1() {
        return this.payments1;
    }

    public void setPayments1(List<Payment> payments1) {
        this.payments1 = payments1;
    }

}
