/**
 * This file was generated by the JPA Modeler
 */
package com.hellokoding.account.Models;

import org.springframework.transaction.annotation.Transactional;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "productitems")
@Transactional
public class ProductItems implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "MP", table = "productitems", precision = 12)
    @Basic
    private Float mp;

    @Column(name = "OTP", table = "productitems", precision = 12)
    @Basic
    private Float otp;

    @Column(name = "MPWithTaxandDiscont", table = "productitems", precision = 12)
    @Basic
    private Float MPWithTaxandDiscont;

    @Column(name = "OTPWithTaxandDiscont", table = "productitems", precision = 12)
    @Basic
    private Float OTPWithTaxandDiscont;

    @ManyToOne(targetEntity = Soproduct.class)
    private Soproduct soproduct1;

    @ManyToOne(targetEntity = OrdItem.class)
    private OrdItem ordItem;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Soproduct getSoproduct1() {
        return this.soproduct1;
    }

    public void setSoproduct1(Soproduct soproduct1) {
        this.soproduct1 = soproduct1;
    }


    public Float getMp() {
        return mp;
    }

    public void setMp(Float mp) {
        this.mp = mp;
    }

    public Float getOtp() {
        return otp;
    }

    public void setOtp(Float otp) {
        this.otp = otp;
    }

    public Float getMPWithTaxandDiscont() {
        return MPWithTaxandDiscont;
    }

    public void setMPWithTaxandDiscont(Float MPWithTaxandDiscont) {
        this.MPWithTaxandDiscont = MPWithTaxandDiscont;
    }

    public Float getOTPWithTaxandDiscont() {
        return OTPWithTaxandDiscont;
    }

    public void setOTPWithTaxandDiscont(Float OTPWithTaxandDiscont) {
        this.OTPWithTaxandDiscont = OTPWithTaxandDiscont;
    }

    public com.hellokoding.account.Models.OrdItem getOrdItem() {
        return ordItem;
    }

    public void setOrdItem(com.hellokoding.account.Models.OrdItem ordItem) {
        this.ordItem = ordItem;
    }
}
