/**
 * This file was generated by the JPA Modeler
 */
package com.hellokoding.account.Models;

import com.hellokoding.account.model.User;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "so")
public class So implements Serializable {

    @Column(name = "SOId", table = "so", nullable = false)
    @Id
    private Integer sOId;

    @Column(name = "DateCreated", table = "so")
    @Basic
    private String dateCreated;

    @Column(name = "OrderDate", table = "so")
    @Basic
    private String orderDate;

    @Column(name = "Status", table = "so")
    @Basic
    private String status;

    @Column(name = "SONumber", table = "so")
    @Basic
    private String SONumber;

    @Column(name = "PurchaseOrderNumber", table = "so")
    @Basic
    private String purchaseOrderNumber;

    @Column(name = "DateModified", table = "so")
    @Basic
    private String dateModified;

    @ManyToOne(targetEntity = Customer.class)
    private Customer customer1;

    @ManyToOne(targetEntity = User.class)
    private User uuser11;

    @OneToMany(targetEntity = Payment.class, mappedBy = "so1")
    private List<Payment> payments1;

    @OneToMany(targetEntity = Soproduct.class, mappedBy = "so1")
    private List<Soproduct> soproducts1;

    public Integer getSOId() {
        return this.sOId;
    }

    public void setSOId(Integer sOId) {
        this.sOId = sOId;
    }

    public String getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSONumber() {
        return this.SONumber;
    }

    public void setSONumber(String SONumber) {
        this.SONumber = SONumber;
    }

    public String getPurchaseOrderNumber() {
        return this.purchaseOrderNumber;
    }

    public void setPurchaseOrderNumber(String purchaseOrderNumber) {
        this.purchaseOrderNumber = purchaseOrderNumber;
    }

    public String getDateModified() {
        return this.dateModified;
    }

    public void setDateModified(String dateModified) {
        this.dateModified = dateModified;
    }

    public Customer getCustomer1() {
        return this.customer1;
    }

    public void setCustomer1(Customer customer1) {
        this.customer1 = customer1;
    }

    public User getUuser11() {
        return this.uuser11;
    }

    public void setUuser11(User uuser11) {
        this.uuser11 = uuser11;
    }

    public List<Payment> getPayments1() {
        return this.payments1;
    }

    public void setPayments1(List<Payment> payments1) {
        this.payments1 = payments1;
    }

    public List<Soproduct> getSoproducts1() {
        return this.soproducts1;
    }

    public void setSoproducts1(List<Soproduct> soproducts1) {
        this.soproducts1 = soproducts1;
    }

}
