/**
 * This file was generated by the JPA Modeler
 */
package com.hellokoding.account.Models;

import com.hellokoding.account.model.User;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "so")
@Transactional
public class So implements Serializable {

    @Column(name = "SOId", table = "so", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long sOId;

    @Column(name = "DateCreated", table = "so")
    @Basic
    private String dateCreated;

    @Column(name = "OrderDate", table = "so")
    @Basic
    private String orderDate;

    @Column(name = "Status", table = "so")
    @Basic
    private String status;

    @Column(name = "SONumber", table = "so")
    @Basic
    private String SONumber;

    @Column(name = "PurchaseOrderNumber", table = "so")
    @Basic
    private String purchaseOrderNumber;

    @Column(name = "DateModified", table = "so")
    @Basic
    private String dateModified;

    @Column(name = "FinalMP", table = "so")
    @Basic
    private BigDecimal finalMP;

    @Column(name = "FinalOTP", table = "so")
    @Basic
    private BigDecimal finalOTP;

    @Column(name = "FinalMPwithTaxAndDiscount", table = "so")
    @Basic
    private BigDecimal finalMPwithTaxAndDiscount;

    @Column(name = "FinalOTPwithTaxAndDiscount", table = "so")
    @Basic
    private BigDecimal finalOTPwithTaxAndDiscount;

    @Column(name = "Location", table = "so")
    @Basic
    private String location;

    @ManyToOne(targetEntity = Customer.class)
    private Customer customer1;

    @OneToMany(targetEntity = Payment.class, mappedBy = "so1")
    private List<Payment> payments1;

    @OneToMany(targetEntity = Soproduct.class, mappedBy = "so1")
    private List<Soproduct> soproducts1;

    public Long getSOId() {
        return this.sOId;
    }

    public void setSOId(Long sOId) {
        this.sOId = sOId;
    }

    public String getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSONumber() {
        return this.SONumber;
    }

    public void setSONumber(String SONumber) {
        this.SONumber = SONumber;
    }

    public String getPurchaseOrderNumber() {
        return this.purchaseOrderNumber;
    }

    public void setPurchaseOrderNumber(String purchaseOrderNumber) {
        this.purchaseOrderNumber = purchaseOrderNumber;
    }

    public String getDateModified() {
        return this.dateModified;
    }

    public void setDateModified(String dateModified) {
        this.dateModified = dateModified;
    }

    public Customer getCustomer1() {
        return this.customer1;
    }

    public void setCustomer1(Customer customer1) {
        this.customer1 = customer1;
    }

    public List<Payment> getPayments1() {
        return this.payments1;
    }

    public void setPayments1(List<Payment> payments1) {
        this.payments1 = payments1;
    }

    public List<Soproduct> getSoproducts1() {
        return this.soproducts1;
    }

    public void setSoproducts1(List<Soproduct> soproducts1) {
        this.soproducts1 = soproducts1;
    }

    public BigDecimal getFinalMP() {
        return finalMP;
    }

    public void setFinalMP(BigDecimal finalMP) {
        this.finalMP = finalMP;
    }

    public BigDecimal getFinalOTP() {
        return finalOTP;
    }

    public void setFinalOTP(BigDecimal finalOTP) {
        this.finalOTP = finalOTP;
    }

    public BigDecimal getFinalMPwithTaxAndDiscount() {
        return finalMPwithTaxAndDiscount;
    }

    public void setFinalMPwithTaxAndDiscount(BigDecimal finalMPwithTaxAndDiscount) {
        this.finalMPwithTaxAndDiscount = finalMPwithTaxAndDiscount;
    }

    public BigDecimal getFinalOTPwithTaxAndDiscount() {
        return finalOTPwithTaxAndDiscount;
    }

    public void setFinalOTPwithTaxAndDiscount(BigDecimal finalOTPwithTaxAndDiscount) {
        this.finalOTPwithTaxAndDiscount = finalOTPwithTaxAndDiscount;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
}
