/**
 * This file was generated by the JPA Modeler
 */
package com.hellokoding.account.Models;

import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "soproduct")
@Transactional
public class Soproduct implements Serializable {

    @Column(name = "SOPId", table = "soproduct", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long sOPId;

    @ManyToOne(targetEntity = So.class)
    private So so1;

    @OneToMany(targetEntity = ProductItems.class, mappedBy = "soproduct1")
    private List<ProductItems> productItemses1;

    public Long getSOPId() {
        return this.sOPId;
    }

    public void setSOPId(Long sOPId) {
        this.sOPId = sOPId;
    }

    public So getSo1() {
        return this.so1;
    }

    public void setSo1(So so1) {
        this.so1 = so1;
    }

    public List<ProductItems> getProductItemses1() {
        return this.productItemses1;
    }

    public void setProductItemses1(List<ProductItems> productItemses1) {
        this.productItemses1 = productItemses1;
    }

}
