/**
 * This file was generated by the JPA Modeler
 */
package com.hellokoding.account.Models;

import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "statisticscollector")
@Transactional
public class Statisticscollector implements Serializable {

    @Column(name = "SCId", table = "statisticscollector", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long SCId;

    @Column(name = "StatisticType", table = "statisticscollector")
    @Basic
    private String statisticType;

    @Column(name = "StatisticsInfo", table = "statisticscollector")
    @Basic
    private String statisticsInfo;

    @ManyToOne(targetEntity = Customer.class)
    private Customer customer1;

    public Long getSCId() {
        return this.SCId;
    }

    public void setSCId(Long SCId) {
        this.SCId = SCId;
    }

    public String getStatisticType() {
        return this.statisticType;
    }

    public void setStatisticType(String statisticType) {
        this.statisticType = statisticType;
    }

    public String getStatisticsInfo() {
        return this.statisticsInfo;
    }

    public void setStatisticsInfo(String statisticsInfo) {
        this.statisticsInfo = statisticsInfo;
    }

    public Customer getCustomer1() {
        return this.customer1;
    }

    public void setCustomer1(Customer customer1) {
        this.customer1 = customer1;
    }

}
